inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

# This allows a longer LineLength whilst ignoring cuke definitions
Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^Given'
    - '^When'
    - '^Then'

# We need to massively improve this! But for now the suite is not under active documentation
Style/Documentation:
  Enabled: false

# We are a DSL, so we occasionally need to use `#set_` prefixes on our DSL names
Naming/AccessorMethodName:
  Enabled: false

# This is a better style, and should be the default IMO
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

# Our gemspec like most will cause issues here
# All spec files are huge blocks, should just ignore them
Metrics/BlockLength:
  Exclude:
    - './spec/**/*_spec.rb'
    - 'site_prism.gemspec'

# Stylistic preference to improve git diffs
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

# Stylistic preference to improve git diffs
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

# See: https://github.com/rubocop-hq/rubocop/issues/5953
# Bug in the way rubocop uses this specific cop
Style/AccessModifierDeclarations:
  Enabled: false

# Stylistic preference to make the RSpec tests flow better
RSpec/MessageSpies:
  EnforcedStyle: receive

# These 2 failures will be fixed when we migrate to Ruby 2.5+ restriction
RSpec/ExampleLength:
  Exclude:
    - 'spec/site_prism/loadable_spec.rb'