require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^Given'
    - '^When'
    - '^Then'

Documentation:
  Enabled: false

AccessorMethodName:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

BlockLength:
  Exclude:
    - './spec/**/*_spec.rb'
    - 'site_prism.gemspec'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

# See: https://github.com/rubocop-hq/rubocop/issues/5953
# Bug in the way rubocop uses this specific cop
Style/AccessModifierDeclarations:
  Enabled: false

# Probably need to look into this, see if we can optimise it down the line
Metrics/ModuleLength:
  Exclude:
    - 'lib/site_prism/dsl.rb'
