language: ruby

sudo: required

dist: xenial

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

env:
  - browser=chrome
  - browser=firefox

gemfile:
  - Gemfile
  - gemfiles/Gemfile.low_spec
  - gemfiles/Gemfile.selenium-3.7

addons:
  chrome: stable
  firefox: latest

before_install:
  - gem install bundler -v '< 2'

services:
  - xvfb

script:
  - bundle exec rake

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
